packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@nestjs/core'
  - '@prisma/engines'
  - browser-tabs-lock
  - bufferutil
  - core-js
  - prisma
  - utf-8-validate
